apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-container
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-container
  template:
    metadata:
      labels:
        app: react-container
    spec:
      containers:
      - name: react-container
        image: mecskyverse/flat-react-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8000